name = 'cardapi'
type = "javascript"

# 请修改成自己的 account_id
account_id = "7439912066299e662e047cd30d8ed533"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-10-02"

# 请修改成自己的 KV 数据库 ID
[[kv_namespaces]]
binding = "JSONBASE"
id = "6455d99d8ea94f2f88244d100fa89f6e"
